#!/usr/bin/env python3

'''
This is a script by Julia Evans cf You Tube Vim with me: Julia Evans
on Changelog's channel.

What it does:
    Highlight lines using Visual
    then :!header
this will turn

meohmy
meohmy

into

###########
##  meohmy #
##  meohmy #
###########

This works because this file is (must be) located in /bin
with chmod set to x
and chown set to donagh:donagh
(These permissions mean that vim is not going to balk at running a script from /bin)

This is a method of utilising python in vim

'''

import fileinput

lines = [x.strip().rstrip(' #').lstrip('# ') for x in fileinput.input()]
line_len = max(len(line) for line in lines)
total_len = line_len + 5

print('#' * total_len)

for line in lines:
    if len(line) == 0:
        continue
    print('## ', end=' ')
    print(line, end='')
    print(' ' * (line_len - len(line)), end='')
    print(' #')

print('#' * total_len)
