keyboard.send_keys('cd')
keyboard.send_keys('<ctrl>+l')

#keyboard.send_keys('<enter>')
#keyboard.send_keys('/n')
#keyboard.press_key('<ctrl>+l')
#keyboard.press_key('<enter>')
#keyboard.release_key('<enter>')
#keyboard.release_key('<ctrl>')
#keyboard.send_keys('<ctrl>+l')