* frontmatter
#+TITLE: Notes for spacemacs
#+TAGS: help orgmode donaghs
#+DATE: 2020-05-08
#+AUTHOR: Donagh McCarthy
#+OPTIONS: num:nil 
#+OPTIONS: html-style:nil
** styling html export
   to export , , h
    #+begin_export html
      <style>
      body {
        color: red;
      }
      </style>

      #+end_export
   source code not displayed


* spacemacs notes
** characters
*** LaTeX
   - Characters: \alpha \rightarrow \beta
** drawers
   Types of drawers:
   - Custom made - see mydrawer below
     To open/close, place cursor on the : line and TAB
     :mydrawer:
  This is the content of my first drawer
  :end:
   - Reserved e.g.  properties drawer, 
** files
*** save [SPC] f s 
*** find files [SPC] f f
*** copy file [SPC] f c
*** filepath [SPC] f y 
     full filepath and places it in the clipboard for copying - /home/donagh/PORTABLE_ENV/spacemacs/spacemacs_notes.org
** folding
*** use the vim system: zc, zo, zm, zr for opening and closing folds.
*** or use S-TAB to cycle through folds
** formatting
   use the symbols fore and aft OR , x and select
*** bold is *bold*
*** italic is /italic/
*** verbatim is =verbatim= 
*** strikethrough +strikethrough+
*** underline _underline_
*** source code / literate programming
    To insert a snippet for source code: [SPC] i s and select begin_src

    Example 1 emacs-lisp
   #+BEGIN_SRC emacs-lisp
   (+ 3 55)

   #+END_SRC

   #+RESULTS:
   : 58

   and then pressing C-x C-e will show 58 in the mini buffer  

    Example 2 python
   #+BEGIN_SRC python
   print(3+43+43+4)
   

   #+END_SRC 
   C-c C-c inside the code block (not working)
   #+RESULTS:
   : None

** help
*** to get help
   [SPC] h d <varies>
   C-h i     <-- info
   Worg is the org-mode wiki at [[ https://orgmode.org/worg/ ][worg]
** keybindings
   M is the Alt key
   M-x for package install.

** killring / clipboard
   [SPC] r y 
   and then C-j to scroll down to item you want to insert to current buffer

** links
*** [ link ] [ description ]
*** [[www.google.com] [ google.com] the final ] is missing as it would collapse to what you can see on the next line.
*** URLs / links 
    [[https://www.google.com][google.com]]
    [[http://donaghmccarthy.ie][donaghmccarthy.ie]] 
*** images / files
    To view the following image: 
    [file:/home/donagh/Images/chainsaw-haircut.png]
    1. make a vert. split. ( , w v) <-- optional
    2. place cursor inside [] , l
    3. q to cancel image
    Link to a file
    # C-c l to make a link in the link store
    # , l to find and open that link
    [[/home/donagh/PORTABLE_ENV/spacemacs][link to .spacemacs in PORTABLE_ENV]]
    
*** C-c C-l will allow to make a link. Link:  & Description:
   [[http://www.donaghmccarthy.ie][donaghmccarthy.ie]] 

** multiple org files
   Suppose you have many files that you want org-mode to 'watch'. In the dotspacemacs-configuration-layers of .spacemacs:
   Say, work, school and home.
#+BEGIN_SRC elisp
(setq org-agenda-files (list "~/org/work.org"
"~/org/school.org" 
                             "~/org/home.org"))
#+END_SRC
Press C-c a t to enter the global todo list.

** navigating
*** within a file
    [SPC] j l then type link to the line (try it!)
    will show links for every file visible in every window! 
*** directory 
    [SPC] f t to see directory tree and q to quit
** options

   Placed at start of file
*** title
    "#+TITLE: 
*** options
    "#+OPTIONS: html-style: nil
*** startip
    "#+STARTIP: overview
** org-capture
   For keeping notes, snippets, thoughts etc.
   org-capture --> , c
   Customize templates --> , c C
   
** org-mode
*** See  /home/donagh/TODO/ORG-MODE/first.org for my preliminary notes on org-mode.
*** Make a new item a todo with t
*** TODO I created a new todo task when on the above line with A-S RET
    DEADLINE: <2020-05-10 Sun>
*** TODO and in insert mode...
    SCHEDULED: <2020-05-12 Tue>
*** to view agenda beyond this week: eg next fortnight --> 14 , a n
    Here's a link with good answers
    https://stackoverflow.com/questions/32423127/how-to-view-the-next-days-in-org-modes-agenda#32426234
*** TODO [1/2] [50%] progress markers - without checkboxes
**** DONE item 1
     CLOSED: [2020-05-15 Fri 15:43]
**** item 2
**** TODO item 3
*** TODO Repeat schedule - e.g.  every week +1w add inside <>
    - Weekly shop
    SCHEDULED: <2020-06-13 Sat +1w>
    NOTE: This doesn't appear in the global TODOS because this file is not "registered" in the list of files to be checked.
** packages
   M-x 
   list-packages (available, installed, builtin )
*** eww
    emacs web browser M-x ew
    w
*** jedi
    server (for python?)
** projects
   *** directory should contain one of these files: .projectile or .git
**** This will allow helm to manage and find the project.

** promoting / demoting 
*** Headings: C-c C-< and C-c C->
*** moving nodes  : M-up and M-down
    
** refresh
   spacemacs --> [SPC] f e R
** shell
*** shell
   Call with  [SPC] !
   There is some issue with .zshrc / .zshenv / PATH which I need to resolve.
*** eshell
    emacs shell
    YouTube video on this at https://www.youtube.com/watch?v=RhYNu6i_uY4
    it's an emacs REPL. e.g. 
    $ (length "Donagh") 
    $ 6

** snippets
   Yasnippet & Yasnippet-snippets
   [SPC] i s
  This is the "incrementally" snippet in text-mode.

** tables
   | Name   | Age | Gender |
   |--------+-----+--------|
   | Donagh |  58 | M      |
   | Helen  |  28 | F      |
   |       |     |        |
** themes
   [SPC] T s to get a new themes
   [SPC] T n to cycle (or toggle) dark / light if only those listed in the spacemacs config under themes.
** windows
*** [SPC] w d to delete a window
*** [SPC] w s to split a window below
*** [SPC] w v to split a window vert. right


donaghs headin
*** g
